package com.izan.backend.mvc.entities;
// Generated 31 mar 2025, 18:29:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name = "empresas", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Empresas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nombre;
	private String direccion;
	private String telefono;
	private Date createdAt;
	private Set<UbicacionesTrabajo> ubicacionesTrabajos = new HashSet<UbicacionesTrabajo>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	@JsonIgnore // 👈 AÑADE ESTO
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public Empresas() {
	}

	public Empresas(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Empresas(int id, String nombre, String direccion, String telefono, Date createdAt, Set<UbicacionesTrabajo> ubicacionesTrabajos,
			Set<Usuarios> usuarioses) {
		this.id = id;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.createdAt = createdAt;
		this.ubicacionesTrabajos = ubicacionesTrabajos;
		this.usuarioses = usuarioses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<UbicacionesTrabajo> getUbicacionesTrabajos() {
		return this.ubicacionesTrabajos;
	}

	public void setUbicacionesTrabajos(Set<UbicacionesTrabajo> ubicacionesTrabajos) {
		this.ubicacionesTrabajos = ubicacionesTrabajos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
