package com.izan.backend.mvc.entities;
// Generated 27 mar 2025, 17:22:11 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Fichajes generated by hbm2java
 */
@Entity
@Table(name = "fichajes", catalog = "worktrack")
public class Fichajes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Usuarios usuarios;
	private String tipo;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private Date fecha;

	public Fichajes() {
	}

	public Fichajes(int id) {
		this.id = id;
	}

	public Fichajes(int id, Usuarios usuarios, String tipo, BigDecimal latitud, BigDecimal longitud, Date fecha) {
		this.id = id;
		this.usuarios = usuarios;
		this.tipo = tipo;
		this.latitud = latitud;
		this.longitud = longitud;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "tipo", length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "latitud", precision = 10, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 10, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
