package com.izan.backend.mvc.entities;
// Generated 31 mar 2025, 18:29:38 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Fichajes generated by hbm2java
 */
@Entity
@Table(name = "fichajes", catalog = "worktrack")
public class Fichajes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Usuarios usuarios;
	private BigDecimal latitudInicio;
	private BigDecimal longitudInicio;
	private Date fechaInicio;
	private BigDecimal latitudFin;
	private BigDecimal longitudFin;
	private Date fechaFin;

	public Fichajes() {
	}

	public Fichajes(Usuarios usuarios, BigDecimal latitudInicio, BigDecimal longitudInicio, Date fechaInicio) {
		this.usuarios = usuarios;
		this.latitudInicio = latitudInicio;
		this.longitudInicio = longitudInicio;
		this.fechaInicio = fechaInicio;
	}

	public Fichajes(Usuarios usuarios, BigDecimal latitudInicio, BigDecimal longitudInicio, Date fechaInicio,
			BigDecimal latitudFin, BigDecimal longitudFin, Date fechaFin) {
		this.usuarios = usuarios;
		this.latitudInicio = latitudInicio;
		this.longitudInicio = longitudInicio;
		this.fechaInicio = fechaInicio;
		this.latitudFin = latitudFin;
		this.longitudFin = longitudFin;
		this.fechaFin = fechaFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "latitud_inicio", nullable = false, precision = 10, scale = 6)
	public BigDecimal getLatitudInicio() {
		return this.latitudInicio;
	}

	public void setLatitudInicio(BigDecimal latitudInicio) {
		this.latitudInicio = latitudInicio;
	}

	@Column(name = "longitud_inicio", nullable = false, precision = 10, scale = 6)
	public BigDecimal getLongitudInicio() {
		return this.longitudInicio;
	}

	public void setLongitudInicio(BigDecimal longitudInicio) {
		this.longitudInicio = longitudInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", nullable = false, length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "latitud_fin", precision = 10, scale = 6)
	public BigDecimal getLatitudFin() {
		return this.latitudFin;
	}

	public void setLatitudFin(BigDecimal latitudFin) {
		this.latitudFin = latitudFin;
	}

	@Column(name = "longitud_fin", precision = 10, scale = 6)
	public BigDecimal getLongitudFin() {
		return this.longitudFin;
	}

	public void setLongitudFin(BigDecimal longitudFin) {
		this.longitudFin = longitudFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
