package com.izan.backend.mvc.entities;
// Generated 31 mar 2025, 18:29:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * HorariosPredefinidos generated by hbm2java
 */
@Entity
@Table(name = "horarios_predefinidos")
public class HorariosPredefinidos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Usuarios usuarios;
	private Byte diaSemana;
	private Date horaInicio;
	private Date horaFin;

	public HorariosPredefinidos() {
	}

	public HorariosPredefinidos(int id) {
		this.id = id;
	}

	public HorariosPredefinidos(int id, Usuarios usuarios, Byte diaSemana, Date horaInicio, Date horaFin) {
		this.id = id;
		this.usuarios = usuarios;
		this.diaSemana = diaSemana;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "dia_semana")
	public Byte getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(Byte diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

}
