package com.izan.backend.mvc.entities;
// Generated 27 mar 2025, 17:22:11 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * TokensRecuperacion generated by hbm2java
 */
@Entity
@Table(name = "tokens_recuperacion", catalog = "worktrack", uniqueConstraints = @UniqueConstraint(columnNames = "token"))
public class TokensRecuperacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Usuarios usuarios;
	private String token;
	private Date expiresAt;
	private Boolean usado;

	public TokensRecuperacion() {
	}

	public TokensRecuperacion(int id, String token, Date expiresAt) {
		this.id = id;
		this.token = token;
		this.expiresAt = expiresAt;
	}

	public TokensRecuperacion(int id, Usuarios usuarios, String token, Date expiresAt, Boolean usado) {
		this.id = id;
		this.usuarios = usuarios;
		this.token = token;
		this.expiresAt = expiresAt;
		this.usado = usado;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "token", unique = true, nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires_at", nullable = false, length = 19)
	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	@Column(name = "usado")
	public Boolean getUsado() {
		return this.usado;
	}

	public void setUsado(Boolean usado) {
		this.usado = usado;
	}

}
