package com.izan.backend.mvc.entities;
// Generated 31 mar 2025, 18:29:38 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * UbicacionesTrabajo generated by hbm2java
 */
@Entity
@Table(name = "ubicaciones_trabajo", catalog = "worktrack")
public class UbicacionesTrabajo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	@ManyToOne
	@JoinColumn(name = "empresa_id") // debe coincidir con tu base de datos
	private Empresas empresa;
	private String nombre;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private Integer radioMetros;

	public UbicacionesTrabajo() {
	}

	public UbicacionesTrabajo(int id, Empresas empresas, String nombre, BigDecimal latitud, BigDecimal longitud) {
		this.id = id;
		this.empresa = empresas;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public UbicacionesTrabajo(int id, Empresas empresas, String nombre, BigDecimal latitud, BigDecimal longitud,
			Integer radioMetros) {
		this.id = id;
		this.empresa = empresas;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.radioMetros = radioMetros;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresas getEmpresa() {
	    return this.empresa;
	}

	public void setEmpresa(Empresas empresa) {
	    this.empresa = empresa;
	}


	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "latitud", nullable = false, precision = 10, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, precision = 10, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Column(name = "radio_metros")
	public Integer getRadioMetros() {
		return this.radioMetros;
	}

	public void setRadioMetros(Integer radioMetros) {
		this.radioMetros = radioMetros;
	}

}
