package com.izan.backend.mvc.entities;
// Generated 31 mar 2025, 18:29:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "worktrack", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Empresas empresas;
	private String nombre;
	private String apellidos;
	private String email;
	private String rol;
	private String telefono;
	private Boolean actividad;
	private Date fechaCreacion;
	private Set<TokensRecuperacion> tokensRecuperacions = new HashSet<TokensRecuperacion>(0);
	private Set<Fichajes> fichajeses = new HashSet<Fichajes>(0);
	private Set<HorariosPredefinidos> horariosPredefinidoses = new HashSet<HorariosPredefinidos>(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String apellidos, String email, String rol) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.rol = rol;
	}

	public Usuarios(Empresas empresas, String nombre, String apellidos, String email, String rol, String telefono,
			Boolean actividad, Date fechaCreacion, Set<TokensRecuperacion> tokensRecuperacions, Set<Fichajes> fichajeses,
			Set<HorariosPredefinidos> horariosPredefinidoses) {
		this.empresas = empresas;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.rol = rol;
		this.telefono = telefono;
		this.actividad = actividad;
		this.fechaCreacion = fechaCreacion;
		this.tokensRecuperacions = tokensRecuperacions;
		this.fichajeses = fichajeses;
		this.horariosPredefinidoses = horariosPredefinidoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id")
	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", nullable = false)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "rol", nullable = false, length = 50)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "actividad")
	public Boolean getActividad() {
		return this.actividad;
	}

	public void setActividad(Boolean actividad) {
		this.actividad = actividad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<TokensRecuperacion> getTokensRecuperacions() {
		return this.tokensRecuperacions;
	}

	public void setTokensRecuperacions(Set<TokensRecuperacion> tokensRecuperacions) {
		this.tokensRecuperacions = tokensRecuperacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Fichajes> getFichajeses() {
		return this.fichajeses;
	}

	public void setFichajeses(Set<Fichajes> fichajeses) {
		this.fichajeses = fichajeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<HorariosPredefinidos> getHorariosPredefinidoses() {
		return this.horariosPredefinidoses;
	}

	public void setHorariosPredefinidoses(Set<HorariosPredefinidos> horariosPredefinidoses) {
		this.horariosPredefinidoses = horariosPredefinidoses;
	}

}
